(function(){function require(name){throw new Error(`无法加载资源-${name}`);}'use strict';var _extends=Object.assign||function(target){for(var i=1;i<arguments.length;i++){var source=arguments[i];for(var key in source){if(Object.prototype.hasOwnProperty.call(source,key)){target[key]=source[key];}}}return target;};var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();var _typeof=typeof Symbol==="function"&&typeof Symbol.iterator==="symbol"?function(obj){return typeof obj;}:function(obj){return obj&&typeof Symbol==="function"&&obj.constructor===Symbol&&obj!==Symbol.prototype?"symbol":typeof obj;};function _asyncToGenerator(fn){return function(){var gen=fn.apply(this,arguments);return new Promise(function(resolve,reject){function step(key,arg){try{var info=gen[key](arg);var value=info.value;}catch(error){reject(error);return;}if(info.done){resolve(value);}else{return Promise.resolve(value).then(function(value){step("next",value);},function(err){step("throw",err);});}}return step("next");});};}
function _toConsumableArray(arr){if(Array.isArray(arr)){for(var i=0,arr2=Array(arr.length);i<arr.length;i++){arr2[i]=arr[i];}return arr2;}else{return Array.from(arr);}}
function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}
var include=function(){var nameRe=/^(\w+)\:{2}(.+?)$/,CODES={};return function(name){if(CODES.hasOwnProperty(name)){return CODES[name];}
var match=name.match(nameRe),folder=void 0,className=void 0;if(match){folder=match[1],className=match[2];}else{folder='src',className=name;}
var fullName=folder+'::'+className,code=CODES[name]=exports[fullName];if(code===undefined&&folder!=='config'){throw new Error(fullName+' \u6CA1\u6709\u5B9A\u4E49');}
return code;};}();exports.include=include;var gettype=function(){var typeofTypes=['number','string','boolean','undefined','function'],toString=Object.prototype.toString,toStringTypes={'[object Array]':'array','[object Date]':'date','[object Boolean]':'boolean','[object Number]':'number','[object RegExp]':'regexp'},nonWhitespaceRe=/\S/;return function(data){if(data===null){return'null';}
var type=typeof data==='undefined'?'undefined':_typeof(data);if(typeofTypes.includes(type)){return type;}
var ret=toStringTypes[toString.call(data)];if(ret){return ret;}
if(type==='object'){if(data.nodeType!==undefined){if(data.nodeType===3){return nonWhitespaceRe.test(data.nodeValue)?'textnode':'whitespace';}else{return'element';}}
return'object';}
return'mixed';};}();var config=function(){function freeze(data){if(data&&(typeof data==='undefined'?'undefined':_typeof(data))==='object'&&!Object.isFrozen(data)){Object.freeze(data);var names=Object.keys(data);var _iteratorNormalCompletion=true;var _didIteratorError=false;var _iteratorError=undefined;try{for(var _iterator=names[Symbol.iterator](),_step;!(_iteratorNormalCompletion=(_step=_iterator.next()).done);_iteratorNormalCompletion=true){var name=_step.value;freeze(data[name]);}}catch(err){_didIteratorError=true;_iteratorError=err;}finally{try{if(!_iteratorNormalCompletion&&_iterator.return){_iterator.return();}}finally{if(_didIteratorError){throw _iteratorError;}}}}
return data;}
var dotRe=/\./g,config={"vue":{"gestures":["browser.event.gesture.tap","browser.event.gesture.drag","browser.event.gesture.swipe"]}};function get_config(target,key){if(key){if(target.hasOwnProperty(key)){return target[key];}
var names=key.split(/\./),prefix='';var _iteratorNormalCompletion2=true;var _didIteratorError2=false;var _iteratorError2=undefined;try{for(var _iterator2=names[Symbol.iterator](),_step2;!(_iteratorNormalCompletion2=(_step2=_iterator2.next()).done);_iteratorNormalCompletion2=true){var name=_step2.value;var _key=''+prefix+name;if(target.hasOwnProperty(_key)){target=target[_key];prefix='';}else{prefix=_key+'.';}}}catch(err){_didIteratorError2=true;_iteratorError2=err;}finally{try{if(!_iteratorNormalCompletion2&&_iterator2.return){_iterator2.return();}}finally{if(_didIteratorError2){throw _iteratorError2;}}}
if(prefix){return;}}
return freeze(target);}
return function(name,key){if(config.hasOwnProperty(name)){return get_config(config[name],key);}
try{return get_config(include('config::'+name),key);}catch(err){}};}();exports['src::browser.event.init']=function(){var __once_1535262521666_value__=void 0,__once_1535262521666_locked__=false;function preventDefault(e){switch(e.target.tagName){case'INPUT':return;}
e.preventDefault();}
function main(target){target.addEventListener('touchstart',preventDefault);target.addEventListener('touchmove',preventDefault);}
return function(){var target=arguments.length>0&&arguments[0]!==undefined?arguments[0]:window;if(__once_1535262521666_locked__){return __once_1535262521666_value__;}
__once_1535262521666_locked__=true;return __once_1535262521666_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target);};}();exports['src::browser.animationFrame.map']=function(){var __once_1535262521666_value__=void 0,__once_1535262521666_locked__=false;function main(){return new Map();}
return function(){if(__once_1535262521666_locked__){return __once_1535262521666_value__;}
__once_1535262521666_locked__=true;return __once_1535262521666_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.animationFrame.set']=function(){var getMap=void 0;var __first_executed_1535262521666__=false;var count=0;function main(fn,scope){count++;var map=getMap(),animationFrame=new AnimationFrame(fn,scope);map.set(count,animationFrame);animationFrame.start();return count;}
var AnimationFrame=function(){function AnimationFrame(fn,scope){_classCallCheck(this,AnimationFrame);var me=this;me.fn=fn;me.scope=scope;}
_createClass(AnimationFrame,[{key:'start',value:function start(){var me=this,fn=me.fn,scope=me.scope,animationFrame=function animationFrame(time){fn.call(scope,time);me.animationFrameId=requestAnimationFrame(animationFrame);};me.animationFrameId=requestAnimationFrame(animationFrame);}},{key:'stop',value:function stop(){cancelAnimationFrame(this.animationFrameId);}}]);return AnimationFrame;}();return function(fn,scope){if(!__first_executed_1535262521666__){getMap=include('browser.animationFrame.map');__first_executed_1535262521666__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),fn,scope);};}();exports['src::is.type']=function(){function main(data,type){return(typeof data==='undefined'?'undefined':_typeof(data))===type;}
return function(data,type){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data,type);};}();exports['src::is.function']=function(){var isType=void 0;var __first_executed_1535262521666__=false;function main(data){return isType(data,'function');}
return function(data){if(!__first_executed_1535262521666__){isType=include('is.type');__first_executed_1535262521666__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::is.object.simple']=function(){function main(data){return data instanceof Object&&data.constructor===Object;}
return function(data){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['config::vue']={"gestures":["browser.event.gesture.tap"]};exports['src::vue.plugin.gestures']=function(){var isFunction=void 0,isObject=void 0,configVue=void 0;var plugins=void 0;var __once_1535262521667_value__=void 0,__once_1535262521667_locked__=false;var __first_executed_1535262521667__=false;var events={};function process_event_name(name){return'touch:'+name;}
function process_event_listener(listener){if(isObject(listener)){if(listener.hasOwnProperty('fn')){var _config=Object.assign({},listener);delete _config.fn;return{fn:listener.fn,config:_config};}}else if(isFunction(listener)){return{fn:listener,config:{}};}
return{};}
function adddEventListener(el,name,listener){var isInstall=arguments.length>3&&arguments[3]!==undefined?arguments[3]:true;name=process_event_name(name);var _process_event_listen=process_event_listener(listener),fn=_process_event_listen.fn,config=_process_event_listen.config;if(isFunction(fn)){if(events.hasOwnProperty(name)){if(isInstall){events[name].install(el,config);}
el.addEventListener(name,fn);}}}
function removeEventListener(el,name,listener){var isUninstall=arguments.length>3&&arguments[3]!==undefined?arguments[3]:true;name=process_event_name(name);var _process_event_listen2=process_event_listener(listener),fn=_process_event_listen2.fn;if(isFunction(fn)){if(events.hasOwnProperty(name)){if(isUninstall){events[name].uninstall(el);}
el.removeEventListener(name,fn);}}}
function bind(el,_ref){var fn=_ref.value,name=_ref.arg;adddEventListener(el,name,fn);}
function unbind(el,_ref2){var fn=_ref2.value,name=_ref2.arg;removeEventListener(el,name,fn);}
function update(el,_ref3){var fn=_ref3.value,oldFn=_ref3.oldValue,name=_ref3.arg;removeEventListener(el,name,oldFn,false),adddEventListener(el,name,fn,false);}
function main(){var _iteratorNormalCompletion3=true;var _didIteratorError3=false;var _iteratorError3=undefined;try{for(var _iterator3=plugins[Symbol.iterator](),_step3;!(_iteratorNormalCompletion3=(_step3=_iterator3.next()).done);_iteratorNormalCompletion3=true){var plugin=_step3.value;plugin=include(plugin);var _plugin=plugin,handledEvents=_plugin.handledEvents;var _iteratorNormalCompletion4=true;var _didIteratorError4=false;var _iteratorError4=undefined;try{for(var _iterator4=handledEvents[Symbol.iterator](),_step4;!(_iteratorNormalCompletion4=(_step4=_iterator4.next()).done);_iteratorNormalCompletion4=true){var handledEvent=_step4.value;events[handledEvent]=plugin;}}catch(err){_didIteratorError4=true;_iteratorError4=err;}finally{try{if(!_iteratorNormalCompletion4&&_iterator4.return){_iterator4.return();}}finally{if(_didIteratorError4){throw _iteratorError4;}}}}}catch(err){_didIteratorError3=true;_iteratorError3=err;}finally{try{if(!_iteratorNormalCompletion3&&_iterator3.return){_iterator3.return();}}finally{if(_didIteratorError3){throw _iteratorError3;}}}
return{install:function install(Vue){Vue.directive('touch',{bind:bind,unbind:unbind,update:update});}};};return function(){if(!__first_executed_1535262521667__){isFunction=include('is.function');isObject=include('is.object.simple');configVue=include('config::vue');plugins=config('vue','gestures');__first_executed_1535262521667__=true;}
if(__once_1535262521667_locked__){return __once_1535262521667_value__;}
__once_1535262521667_locked__=true;return __once_1535262521667_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.event.gesture.tap.properties.handleEvents']=function(){var __once_1535262521667_value__=void 0,__once_1535262521667_locked__=false;function main(){return['touch:beforetap','touch:tap','touch:tapcancel'];}
return function(){if(__once_1535262521667_locked__){return __once_1535262521667_value__;}
__once_1535262521667_locked__=true;return __once_1535262521667_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::os.name']=function(){var __once_1535262521667_value__=void 0,__once_1535262521667_locked__=false;function main(){var NAMES={iphone:'iOS',android:'Android',mac:'MacOS',win:'Windows',linux:'Linux',other:'Other'};var userAgent=navigator.userAgent.toLowerCase(),name=NAMES[(userAgent.match(/mac|win|linux/)||['other'])[0]];switch(name){case'MacOS':case'Linux':{var _name=NAMES[(userAgent.match(/iphone|android/)||['other'])[0]];if(_name!=='Other'){return _name;}}}
return name;}
return function(){if(__once_1535262521667_locked__){return __once_1535262521667_value__;}
__once_1535262521667_locked__=true;return __once_1535262521667_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.embed.name']=function(){var __once_1535262521667_value__=void 0,__once_1535262521667_locked__=false;function main(){var NAMES={ue4:'UE4',unity:'U3D',other:'Other'};return NAMES[(navigator.userAgent.toLowerCase().match(/ue4|unity/)||['other'])[0]];}
return function(){if(__once_1535262521667_locked__){return __once_1535262521667_value__;}
__once_1535262521667_locked__=true;return __once_1535262521667_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.support.touch']=function(){var osName=void 0,getName=void 0;var __once_1535262521667_value__=void 0,__once_1535262521667_locked__=false;var __first_executed_1535262521667__=false;function main(){var isTouch=window.hasOwnProperty('ontouchstart');if(osName()==='Windows'){var name=getName();return isTouch&&name!=='U3D'&&name!=='UE4';}
return isTouch;}
return function(){if(!__first_executed_1535262521667__){osName=include('os.name');getName=include('browser.embed.name');__first_executed_1535262521667__=true;}
if(__once_1535262521667_locked__){return __once_1535262521667_value__;}
__once_1535262521667_locked__=true;return __once_1535262521667_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.event.pointer']=function(){var isTouch=void 0;var __first_executed_1535262521667__=false;function main(e,valid){if(isTouch()){var touches=e.changedTouches;if(valid){if(touches.length==1){return touches[0];}}else{return touches[0];}}
return e;}
return function(e){var valid=arguments.length>1&&arguments[1]!==undefined?arguments[1]:false;if(!__first_executed_1535262521667__){isTouch=include('browser.support.touch');__first_executed_1535262521667__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e,valid);};}();exports['src::array.removeByIndex']=function(){function main(data,index){if(index>=0&&index<data.length){data.splice(index,1);return true;}
return false;}
return function(data,index){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data,index);};}();exports['src::map.event.listener']=function(){var _remove=void 0;var __once_1535262521667_value__=void 0,__once_1535262521667_locked__=false;var __first_executed_1535262521667__=false;function main(){var Map=function(){function Map(){_classCallCheck(this,Map);var me=this;me.functions=[];me.scopes=[];me.results=[];}
_createClass(Map,[{key:'indexOf',value:function indexOf(fn,scope){var functions=this.functions,scopes=this.scopes,len=functions.length;for(var i=0;i<len;i++){if(functions[i]===fn&&scopes[i]===scope){return i;}}
return-1;}},{key:'get',value:function get(fn,scope){var me=this,functions=me.functions,scopes=me.scopes,results=me.results,index=me.indexOf(fn,scope);if(index!==-1){return results[index];}
functions.push(fn);fn=fn.bind(scope);scopes.push(scope);results.push(fn);return fn;}},{key:'remove',value:function remove(fn,scope){var me=this,functions=me.functions,scopes=me.scopes,results=me.results,index=me.indexOf(fn,scope);if(index!==-1){_remove(functions,index);_remove(scopes,index);_remove(results,index);}}}]);return Map;}();return new Map();}
return function(){if(!__first_executed_1535262521667__){_remove=include('array.removeByIndex');__first_executed_1535262521667__=true;}
if(__once_1535262521667_locked__){return __once_1535262521667_value__;}
__once_1535262521667_locked__=true;return __once_1535262521667_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.html.event.listener.add']=function(){var getMap=void 0;var __first_executed_1535262521667__=false;function main(target,event,fn,scope){target.addEventListener(event,getMap().get(fn,scope));}
return function(target,event,fn,scope){if(!__first_executed_1535262521667__){getMap=include('map.event.listener');__first_executed_1535262521667__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,event,fn,scope);};}();exports['src::browser.html.element.addWindowEventListener']=function(){var addEventListener=void 0;var __first_executed_1535262521667__=false;function main(el,event,fn){addEventListener(window,event,fn,el);}
return function(el,event,fn){if(!__first_executed_1535262521667__){addEventListener=include('browser.html.event.listener.add');__first_executed_1535262521667__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,event,fn);};}();exports['src::math.point.distance']=function(){function main(point1,point2){var pow=Math.pow,sqrt=Math.sqrt;return sqrt(pow(point1.x-point2.x,2)+pow(point1.y-point2.y,2),2);}
return function(point1,point2){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),point1,point2);};}();exports['src::browser.html.event.listener.remove']=function(){var getMap=void 0;var __first_executed_1535262521667__=false;function main(target,event,fn,scope){var map=getMap();target.removeEventListener(event,map.get(fn,scope));map.remove(fn,scope);}
return function(target,event,fn,scope){if(!__first_executed_1535262521667__){getMap=include('map.event.listener');__first_executed_1535262521667__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,event,fn,scope);};}();exports['src::browser.html.element.removeWindowEventListener']=function(){var removeEventListener=void 0;var __first_executed_1535262521667__=false;function main(el,event,fn){removeEventListener(window,event,fn,el);}
return function(el,event,fn){if(!__first_executed_1535262521667__){removeEventListener=include('browser.html.event.listener.remove');__first_executed_1535262521667__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,event,fn);};}();exports['src::browser.event.dispatch']=function(){function main(target,name,detail){target.dispatchEvent(new CustomEvent(name,{bubbles:false,detail:detail}));}
return function(target,name,detail){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,name,detail);};}();exports['src::object.data.name.signature']=function(){var __once_1535262521668_value__=void 0,__once_1535262521668_locked__=false;function main(){return'zbee-key-'+Date.now();}
return function(){if(__once_1535262521668_locked__){return __once_1535262521668_value__;}
__once_1535262521668_locked__=true;return __once_1535262521668_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::object.data.name']=function(){var signature=void 0;var __first_executed_1535262521668__=false;function main(name){return signature()+'-'+name;}
return function(name){if(!__first_executed_1535262521668__){signature=include('object.data.name.signature');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),name);};}();exports['src::object.data.get']=function(){var getName=void 0;var __first_executed_1535262521668__=false;function main(target,name){return target[getName(name)];}
return function(target,name){if(!__first_executed_1535262521668__){getName=include('object.data.name');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,name);};}();exports['src::object.data.set']=function(){var getName=void 0;var __first_executed_1535262521668__=false;function main(target,name,value){target[getName(name)]=value;}
return function(target,name,value){if(!__first_executed_1535262521668__){getName=include('object.data.name');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,name,value);};}();exports['src::browser.event.gesture.tap.methods.onEnd']=function(){var disabled=void 0,dispatch=void 0,getEvent=void 0,get=void 0,set=void 0;var __first_executed_1535262521668__=false;function main(e){e.preventDefault();var el=this,event=getEvent(e),defer=get(el,'tap:defer');dispatch(el,'touch:beforetap',{browserEvent:e,event:getEvent(e)});if(defer){set(el,'tap:deferTimer',setTimeout(function(){dispatch(el,'touch:tap',{browserEvent:e,event:getEvent(e)});disabled(el);},defer));}else{dispatch(el,'touch:tap',{browserEvent:e,event:getEvent(e)});disabled(el);}}
return function(e){if(!__first_executed_1535262521668__){disabled=include('browser.event.gesture.tap.methods.disabled');dispatch=include('browser.event.dispatch');getEvent=include('browser.event.pointer');get=include('object.data.get');set=include('object.data.set');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.pointer.move']=function(){var isTouch=void 0;var __once_1535262521668_value__=void 0,__once_1535262521668_locked__=false;var __first_executed_1535262521668__=false;function main(){return isTouch()?'touchmove':'pointermove';}
return function(){if(!__first_executed_1535262521668__){isTouch=include('browser.support.touch');__first_executed_1535262521668__=true;}
if(__once_1535262521668_locked__){return __once_1535262521668_value__;}
__once_1535262521668_locked__=true;return __once_1535262521668_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.event.pointer.up']=function(){var isTouch=void 0;var __once_1535262521668_value__=void 0,__once_1535262521668_locked__=false;var __first_executed_1535262521668__=false;function main(){return isTouch()?'touchend':'pointerup';}
return function(){if(!__first_executed_1535262521668__){isTouch=include('browser.support.touch');__first_executed_1535262521668__=true;}
if(__once_1535262521668_locked__){return __once_1535262521668_value__;}
__once_1535262521668_locked__=true;return __once_1535262521668_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::object.data.remove']=function(){var getName=void 0;var __first_executed_1535262521668__=false;function main(target,name){delete target[getName(name)];}
return function(target,name){if(!__first_executed_1535262521668__){getName=include('object.data.name');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,name);};}();exports['src::browser.event.gesture.tap.methods.disabled']=function(){var removeEventListener=void 0,onMove=void 0,onEnd=void 0,getMoveEventName=void 0,getUpEventName=void 0,get=void 0,remove=void 0,tap=void 0;var __first_executed_1535262521668__=false;function main(el){removeEventListener(el,getMoveEventName(),onMove);removeEventListener(el,getUpEventName(),onEnd);clearTimeout(get(el,'tap:deferTimer'));remove(el,'tap:deferTimer');remove(el,'tap:startPoint');tap.locked=false;}
return function(el){if(!__first_executed_1535262521668__){removeEventListener=include('browser.html.element.removeWindowEventListener');onMove=include('browser.event.gesture.tap.methods.onMove');onEnd=include('browser.event.gesture.tap.methods.onEnd');getMoveEventName=include('browser.event.pointer.move');getUpEventName=include('browser.event.pointer.up');get=include('object.data.get');remove=include('object.data.remove');tap=include('browser.event.gesture.tap');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.scale']=function(){var osName=void 0;var __first_executed_1535262521668__=false;function main(){switch(osName){case'iOS':case'Android':return 1;}
return window.devicePixelRatio;}
return function(){if(!__first_executed_1535262521668__){osName=include('os.name');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['config::gesture.tap']={"timeout":100,"moveDistance":100};exports['src::browser.event.gesture.tap.methods.onMove']=function(){var getEvent=void 0,getDistance=void 0,disabled=void 0,scale=void 0,get=void 0,dispatch=void 0,configGestureTap=void 0;var moveDistance=void 0;var __first_executed_1535262521668__=false;function main(e){e.preventDefault();var el=this,event=getEvent(e);if(Math.round(Math.abs(getDistance({x:event.pageX,y:event.pageY},get(el,'tap:startPoint'))*scale()))>=moveDistance){dispatch(el,'touch:tapcancel',{browserEvent:e,event:event});disabled(el);}}
return function(e){if(!__first_executed_1535262521668__){getEvent=include('browser.event.pointer');getDistance=include('math.point.distance');disabled=include('browser.event.gesture.tap.methods.disabled');scale=include('browser.scale');get=include('object.data.get');dispatch=include('browser.event.dispatch');configGestureTap=include('config::gesture.tap');moveDistance=config('gesture.tap','moveDistance');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.tap.methods.enabled']=function(){var addEventListener=void 0,onMove=void 0,onEnd=void 0,getMoveEventName=void 0,getUpEventName=void 0;var __first_executed_1535262521668__=false;function main(el){addEventListener(el,getMoveEventName(),onMove);addEventListener(el,getUpEventName(),onEnd);}
return function(el){if(!__first_executed_1535262521668__){addEventListener=include('browser.html.element.addWindowEventListener');onMove=include('browser.event.gesture.tap.methods.onMove');onEnd=include('browser.event.gesture.tap.methods.onEnd');getMoveEventName=include('browser.event.pointer.move');getUpEventName=include('browser.event.pointer.up');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::object.data.has']=function(){var getName=void 0;var __first_executed_1535262521668__=false;function main(target,name){return target.hasOwnProperty(getName(name));}
return function(target,name){if(!__first_executed_1535262521668__){getName=include('object.data.name');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,name);};}();exports['src::browser.event.gesture.tap.methods.onStart']=function(){var getEvent=void 0,enabled=void 0,set=void 0,get=void 0,has=void 0,tap=void 0,configGestureTap=void 0;var timeout=void 0;var __first_executed_1535262521668__=false;function main(e){var _tap=tap,locked=_tap.locked,time=_tap.time;if(locked===true){return;}
var currentTime=Date.now();if(time&&currentTime-time<=timeout){return;}
tap.time=currentTime;tap.locked=true;e.preventDefault();var event=getEvent(e,true);if(!event){return;}
var el=this;set(el,'tap:startPoint',{x:event.pageX,y:event.pageY});if(has(el,'tap:defer')){clearTimeout(get(el,'tap:deferTimer'));}
enabled(el);}
return function(e){if(!__first_executed_1535262521668__){getEvent=include('browser.event.pointer');enabled=include('browser.event.gesture.tap.methods.enabled');set=include('object.data.set');get=include('object.data.get');has=include('object.data.has');tap=include('browser.event.gesture.tap');configGestureTap=include('config::gesture.tap');timeout=config('gesture.tap','timeout');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.pointer.down']=function(){var isTouch=void 0;var __once_1535262521668_value__=void 0,__once_1535262521668_locked__=false;var __first_executed_1535262521668__=false;function main(){return isTouch()?'touchstart':'pointerdown';}
return function(){if(!__first_executed_1535262521668__){isTouch=include('browser.support.touch');__first_executed_1535262521668__=true;}
if(__once_1535262521668_locked__){return __once_1535262521668_value__;}
__once_1535262521668_locked__=true;return __once_1535262521668_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.event.gesture.tap.methods.install']=function(){var onStart=void 0,getEventName=void 0,set=void 0;var __first_executed_1535262521668__=false;function main(el,config){if(config){var defer=config.defer;if(defer){set(el,'tap:defer',defer);}}
el.addEventListener(getEventName(),onStart);}
return function(el,config){if(!__first_executed_1535262521668__){onStart=include('browser.event.gesture.tap.methods.onStart');getEventName=include('browser.event.pointer.down');set=include('object.data.set');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,config);};}();exports['src::browser.event.gesture.tap.methods.uninstall']=function(){var onStart=void 0,getEventName=void 0;var __first_executed_1535262521668__=false;function main(el){el.removeEventListener(getEventName(),onStart);}
return function(el){if(!__first_executed_1535262521668__){onStart=include('browser.event.gesture.tap.methods.onStart');getEventName=include('browser.event.pointer.down');__first_executed_1535262521668__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.tap']=function(){var Main=function(){function Main(){_classCallCheck(this,Main);}
_createClass(Main,null,[{key:'install',value:function install(){return include('browser.event.gesture.tap.methods.install').apply(this,arguments);}},{key:'uninstall',value:function uninstall(){return include('browser.event.gesture.tap.methods.uninstall').apply(this,arguments);}},{key:'handledEvents',get:function get(){return include('browser.event.gesture.tap.properties.handleEvents').call(this);}}]);return Main;}();;return Main;}();exports['src::browser.event.gesture.drag.properties.handleEvents']=function(){var __once_1535262521670_value__=void 0,__once_1535262521670_locked__=false;function main(){return['touch:dragstart','touch:drag','touch:dragend'];}
return function(){if(__once_1535262521670_locked__){return __once_1535262521670_value__;}
__once_1535262521670_locked__=true;return __once_1535262521670_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::browser.event.gesture.drag.methods.resetInfo']=function(){var get=void 0;var __first_executed_1535262521670__=false;function main(el,axis){var info=get(el,'drag:info'),value=get(el,'drag:lastPoint')[axis],startPoint=get(el,'drag:startPoint'),startValue=startPoint[axis],delta=value-startValue,capAxis=axis.toUpperCase(),startTime=get(el,'drag:startTime');info.delta[axis]=delta;info.absDelta[axis]=Math.abs(delta);info.previousTime[axis]=startTime;info.previous[axis]=startValue;info[axis]=value;info.direction[axis]=0;info['start'+capAxis]=startPoint[axis];info['previous'+capAxis]=info.previous[axis];info['page'+capAxis]=info[axis];info['delta'+capAxis]=info.delta[axis];info['absDelta'+capAxis]=info.absDelta[axis];info['previousDelta'+capAxis]=0;info.startTime=startTime;}
return function(el,axis){if(!__first_executed_1535262521670__){get=include('object.data.get');__first_executed_1535262521670__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,axis);};}();exports['src::browser.event.gesture.drag.methods.updateInfo']=function(){var get=void 0;var __first_executed_1535262521670__=false;function main(el,axis,updatePrevious){var info=get(el,'drag:info'),time=Date.now(),value=get(el,'drag:lastPoint')[axis],previousValue=get(el,'drag:previousPoint')[axis],startPoint=get(el,'drag:startPoint'),startValue=startPoint[axis],delta=value-startValue,direction=info.direction,capAxis=axis.toUpperCase(),previousFlick=info.previous[axis],previousDelta=void 0;previousDelta=info.delta[axis];info.delta[axis]=delta;info.absDelta[axis]=Math.abs(delta);if(updatePrevious&&value!==previousFlick&&value!==info[axis]&&time-info.previousTime[axis]>=50){info.previous[axis]=info[axis];info.previousTime[axis]=info.time;}
info[axis]=value;if(value>previousValue){direction[axis]=1;}else if(value<previousValue){direction[axis]=-1;}
info['start'+capAxis]=startPoint[axis];info['previous'+capAxis]=info.previous[axis];info['page'+capAxis]=info[axis];info['delta'+capAxis]=info.delta[axis];info['absDelta'+capAxis]=info.absDelta[axis];info['previousDelta'+capAxis]=previousDelta;info.startTime=get(el,'drag:startTime');}
return function(el,axis,updatePrevious){if(!__first_executed_1535262521670__){get=include('object.data.get');__first_executed_1535262521670__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,axis,updatePrevious);};}();exports['src::browser.event.gesture.drag.methods.onDragMove']=function(){var get=void 0,set=void 0,has=void 0,updateInfo=void 0,getEvent=void 0,dispatch=void 0;var __first_executed_1535262521670__=false;function main(e){e.preventDefault();var event=getEvent(e),el=this;if(has(el,'drag:lastPoint')){set(el,'drag:previousPoint',get(el,'drag:lastPoint'));}
set(el,'drag:lastPoint',{x:event.pageX,y:event.pageY});updateInfo(el,'x',true);updateInfo(el,'y',true);var info=get(el,'drag:info');info.time=Date.now();dispatch(el,'touch:drag',{event:event,browserEvent:e,info:info});}
return function(e){if(!__first_executed_1535262521670__){get=include('object.data.get');set=include('object.data.set');has=include('object.data.has');updateInfo=include('browser.event.gesture.drag.methods.updateInfo');getEvent=include('browser.event.pointer');dispatch=include('browser.event.dispatch');__first_executed_1535262521670__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.drag.methods.onAxisDragEnd']=function(){function main(axis,info){var duration=info.time-info.previousTime[axis];if(duration>0){info.flick.velocity[axis]=(info[axis]-info.previous[axis])/duration;}}
return function(axis,info){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),axis,info);};}();exports['src::browser.event.gesture.drag.methods.onEnd']=function(){var get=void 0,set=void 0,remove=void 0,getEvent=void 0,updateInfo=void 0,onAxisDragEnd=void 0,getMoveEventName=void 0,getEndEventName=void 0,onDragMove=void 0,onEnd=void 0,dispatch=void 0,removeEventListener=void 0;var __first_executed_1535262521670__=false;function main(e){e.preventDefault();var el=this,event=getEvent(e),info=get(el,'drag:info');set(el,'drag:lastPoint',{x:event.pageX,y:event.pageY});updateInfo(el,'x');updateInfo(el,'y');info.time=Date.now();onAxisDragEnd('x',info);onAxisDragEnd('y',info);dispatch(el,'touch:dragend',{event:event,browserEvent:e,info:info});removeEventListener(el,getMoveEventName(),onDragMove),removeEventListener(el,getEndEventName(),onEnd);remove(el,'drag:info');remove(el,'drag:lastPoint');remove(el,'drag:previousPoint');remove(el,'drag:startTime');remove(el,'drag:startPoint');}
return function(e){if(!__first_executed_1535262521670__){get=include('object.data.get');set=include('object.data.set');remove=include('object.data.remove');getEvent=include('browser.event.pointer');updateInfo=include('browser.event.gesture.drag.methods.updateInfo');onAxisDragEnd=include('browser.event.gesture.drag.methods.onAxisDragEnd');getMoveEventName=include('browser.event.pointer.move');getEndEventName=include('browser.event.pointer.up');onDragMove=include('browser.event.gesture.drag.methods.onDragMove');onEnd=include('browser.event.gesture.drag.methods.onEnd');dispatch=include('browser.event.dispatch');removeEventListener=include('browser.html.element.removeWindowEventListener');__first_executed_1535262521670__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['config::gesture.drag']={"minDistance":8};exports['src::browser.event.gesture.drag.methods.onMove']=function(){var set=void 0,get=void 0,getEvent=void 0,scale=void 0,resetInfo=void 0,getMoveEventName=void 0,getEndEventName=void 0,addEventListener=void 0,removeEventListener=void 0,onMove=void 0,onDragMove=void 0,onEnd=void 0,distance=void 0,dispatch=void 0,configGestureDrag=void 0;var minDistance=void 0;var __first_executed_1535262521670__=false;function main(e){e.preventDefault();var event=getEvent(e,true),el=this,info=get(el,'drag:info'),point={x:event.pageX,y:event.pageY};if(Math.round(distance(get(el,'drag:startPoint'),point)*scale())>=minDistance){set(el,'drag:previousPoint',point);set(el,'drag:lastPoint',point);resetInfo(el,'x');resetInfo(el,'y');info.time=Date.now();dispatch(el,'touch:dragstart',{browserEvent:e,event:event,info:info});var moveEventName=getMoveEventName();removeEventListener(el,moveEventName,onMove);addEventListener(el,moveEventName,onDragMove);addEventListener(el,getEndEventName(),onEnd);}}
return function(e){if(!__first_executed_1535262521670__){set=include('object.data.set');get=include('object.data.get');getEvent=include('browser.event.pointer');scale=include('browser.scale');resetInfo=include('browser.event.gesture.drag.methods.resetInfo');getMoveEventName=include('browser.event.pointer.move');getEndEventName=include('browser.event.pointer.up');addEventListener=include('browser.html.element.addWindowEventListener');removeEventListener=include('browser.html.element.removeWindowEventListener');onMove=include('browser.event.gesture.drag.methods.onMove');onDragMove=include('browser.event.gesture.drag.methods.onDragMove');onEnd=include('browser.event.gesture.drag.methods.onEnd');distance=include('math.point.distance');dispatch=include('browser.event.dispatch');configGestureDrag=include('config::gesture.drag');minDistance=config('gesture.drag','minDistance');__first_executed_1535262521670__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.drag.methods.onStart']=function(){var set=void 0,getEvent=void 0,addEventListener=void 0,onMove=void 0,getEventName=void 0;var __first_executed_1535262521671__=false;function main(e){e.preventDefault();var event=getEvent(e,true);if(!event){return;}
var el=this;set(el,'drag:info',{previous:{x:0,y:0},x:0,y:0,delta:{x:0,y:0},absDelta:{x:0,y:0},flick:{velocity:{x:0,y:0}},direction:{x:0,y:0},time:0,previousTime:{x:0,y:0}}),set(el,'drag:startTime',Date.now()),set(el,'drag:startPoint',{x:event.pageX,y:event.pageY});addEventListener(el,getEventName(),onMove);}
return function(e){if(!__first_executed_1535262521671__){set=include('object.data.set');getEvent=include('browser.event.pointer');addEventListener=include('browser.html.element.addWindowEventListener');onMove=include('browser.event.gesture.drag.methods.onMove');getEventName=include('browser.event.pointer.move');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.drag.methods.install']=function(){var onStart=void 0,getEventName=void 0;var __first_executed_1535262521671__=false;function main(el){el.addEventListener(getEventName(),onStart);}
return function(el){if(!__first_executed_1535262521671__){onStart=include('browser.event.gesture.drag.methods.onStart');getEventName=include('browser.event.pointer.down');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.drag.methods.uninstall']=function(){var onStart=void 0,getEventName=void 0;var __first_executed_1535262521671__=false;function main(el){el.removeEventListener(getEventName(),onStart);}
return function(el){if(!__first_executed_1535262521671__){onStart=include('browser.event.gesture.drag.methods.onStart');getEventName=include('browser.event.pointer.down');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.drag']=function(){var Main=function(){function Main(){_classCallCheck(this,Main);}
_createClass(Main,null,[{key:'install',value:function install(){return include('browser.event.gesture.drag.methods.install').apply(this,arguments);}},{key:'uninstall',value:function uninstall(){return include('browser.event.gesture.drag.methods.uninstall').apply(this,arguments);}},{key:'handledEvents',get:function get(){return include('browser.event.gesture.drag.properties.handleEvents').call(this);}}]);return Main;}();;return Main;}();exports['src::browser.event.gesture.swipe.properties.handleEvents']=function(){var __once_1535262521671_value__=void 0,__once_1535262521671_locked__=false;function main(){return['touch:swipestart','touch:swipe','touch:swipecancel'];}
return function(){if(__once_1535262521671_locked__){return __once_1535262521671_value__;}
__once_1535262521671_locked__=true;return __once_1535262521671_value__=main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['config::gesture.swipe']={"moveDistance":8,"minDistance":80,"maxOffset":35,"maxDuration":1000};exports['src::browser.event.gesture.swipe.methods.onEnd']=function(){var cancel=void 0,disabled=void 0,dispatch=void 0,getEvent=void 0,get=void 0,set=void 0,configGestureSwipe=void 0;var maxDuration=void 0,moveDistance=void 0,minDistance=void 0,maxOffset=void 0;var __first_executed_1535262521671__=false;function main(e){e.preventDefault();var el=this,event=getEvent(e),x=event.pageX,y=event.pageY,deltaX=x-get(el,'swipe:startX'),deltaY=y-get(el,'swipe:startY'),absDeltaX=Math.abs(deltaX),absDeltaY=Math.abs(deltaY),duration=Date.now()-get(el,'swipe:startTime'),isHorizontal=get(el,'swipe:isHorizontal'),isVertical=get(el,'swipe:isVertical'),direction=void 0,distance=void 0;if(isVertical&&absDeltaY<minDistance){set(el,'swipe:isVertical',isVertical=false);}
if(isHorizontal&&absDeltaX<minDistance){set(el,'swipe:isHorizontal',isHorizontal=false);}
if(isHorizontal){direction=deltaX<0?'left':'right';distance=absDeltaX;}else if(isVertical){direction=deltaY<0?'up':'down';distance=absDeltaY;}
if(!isHorizontal&&!isVertical){return cancel(el,event,e);}
disabled(el);dispatch(el,'touch:swipe',{browserEvent:e,event:event,direction:direction,distance:distance,duration:duration});}
return function(e){if(!__first_executed_1535262521671__){cancel=include('browser.event.gesture.swipe.methods.cancel');disabled=include('browser.event.gesture.swipe.methods.disabled');dispatch=include('browser.event.dispatch');getEvent=include('browser.event.pointer');get=include('object.data.get');set=include('object.data.set');configGestureSwipe=include('config::gesture.swipe');configGestureSwipe=include('config::gesture.swipe');configGestureSwipe=include('config::gesture.swipe');configGestureSwipe=include('config::gesture.swipe');maxDuration=config('gesture.swipe','maxDuration');moveDistance=config('gesture.swipe','moveDistance');minDistance=config('gesture.swipe','minDistance');maxOffset=config('gesture.swipe','maxOffset');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.swipe.methods.disabled']=function(){var removeEventListener=void 0,onMove=void 0,onEnd=void 0,getMoveEventName=void 0,getUpEventName=void 0,get=void 0,remove=void 0;var __first_executed_1535262521671__=false;function main(el){removeEventListener(el,getMoveEventName(),onMove);removeEventListener(el,getUpEventName(),onEnd);remove(el,'swipe:startTime');remove(el,'swipe:isHorizontal');remove(el,'swipe:isVertical');remove(el,'swipe:startX');remove(el,'swipe:startY');}
return function(el){if(!__first_executed_1535262521671__){removeEventListener=include('browser.html.element.removeWindowEventListener');onMove=include('browser.event.gesture.swipe.methods.onMove');onEnd=include('browser.event.gesture.swipe.methods.onEnd');getMoveEventName=include('browser.event.pointer.move');getUpEventName=include('browser.event.pointer.up');get=include('object.data.get');remove=include('object.data.remove');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.swipe.methods.cancel']=function(){var disabled=void 0,dispatch=void 0;var __first_executed_1535262521671__=false;function main(el,event,e){disabled(el);dispatch(el,'touch:swipecancel',{browserEvent:e,event:event});}
return function(el,event,e){if(!__first_executed_1535262521671__){disabled=include('browser.event.gesture.swipe.methods.disabled');dispatch=include('browser.event.dispatch');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,event,e);};}();exports['src::browser.event.gesture.swipe.methods.onMove']=function(){var getEvent=void 0,cancel=void 0,get=void 0,set=void 0,dispatch=void 0,removeEventListener=void 0,onMove=void 0,getMoveEventName=void 0,supportTouch=void 0,configGestureSwipe=void 0;var maxDuration=void 0,moveDistance=void 0,minDistance=void 0,maxOffset=void 0;var __first_executed_1535262521671__=false;function main(e){e.preventDefault();var el=this,event=getEvent(e),x=event.pageX,y=event.pageY,deltaX=x-get(el,'swipe:startX'),deltaY=y-get(el,'swipe:startY'),absDeltaX=Math.abs(deltaX),absDeltaY=Math.abs(deltaY),duration=Date.now()-get(el,'swipe:startTime'),isHorizontal=get(el,'swipe:isHorizontal'),isVertical=get(el,'swipe:isVertical'),direction=void 0,distance=void 0;if(supportTouch()&&absDeltaX===0&&absDeltaY===0||duration>maxDuration){return cancel(el,event,e);}
if(isHorizontal&&absDeltaY>maxOffset){set(el,'swipe:isHorizontal',isHorizontal=false);}
if(isVertical&&absDeltaX>maxOffset){set(el,'swipe:isVertical',isVertical=false);}
if(!isHorizontal&&!isVertical){return cancel(el,event,e);}
if(!isVertical||!isHorizontal){if(isHorizontal&&absDeltaX<minDistance){direction=deltaX<0?'left':'right';distance=absDeltaX;}else if(isVertical&&absDeltaY<minDistance){direction=deltaY<0?'up':'down';distance=absDeltaY;}}
if(direction){removeEventListener(el,getMoveEventName(),onMove);dispatch(el,'touch:swipestart',{browserEvent:e,event:event,direction:direction,distance:distance,duration:duration});}}
return function(e){if(!__first_executed_1535262521671__){getEvent=include('browser.event.pointer');cancel=include('browser.event.gesture.swipe.methods.cancel');get=include('object.data.get');set=include('object.data.set');dispatch=include('browser.event.dispatch');removeEventListener=include('browser.html.element.removeWindowEventListener');onMove=include('browser.event.gesture.swipe.methods.onMove');getMoveEventName=include('browser.event.pointer.move');supportTouch=include('browser.support.touch');configGestureSwipe=include('config::gesture.swipe');configGestureSwipe=include('config::gesture.swipe');configGestureSwipe=include('config::gesture.swipe');configGestureSwipe=include('config::gesture.swipe');maxDuration=config('gesture.swipe','maxDuration');moveDistance=config('gesture.swipe','moveDistance');minDistance=config('gesture.swipe','minDistance');maxOffset=config('gesture.swipe','maxOffset');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.swipe.methods.enabled']=function(){var addEventListener=void 0,onMove=void 0,onEnd=void 0,getMoveEventName=void 0,getUpEventName=void 0;var __first_executed_1535262521671__=false;function main(el){addEventListener(el,getMoveEventName(),onMove);addEventListener(el,getUpEventName(),onEnd);}
return function(el){if(!__first_executed_1535262521671__){addEventListener=include('browser.html.element.addWindowEventListener');onMove=include('browser.event.gesture.swipe.methods.onMove');onEnd=include('browser.event.gesture.swipe.methods.onEnd');getMoveEventName=include('browser.event.pointer.move');getUpEventName=include('browser.event.pointer.up');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.swipe.methods.onStart']=function(){var getEvent=void 0,enabled=void 0,set=void 0;var __first_executed_1535262521671__=false;function main(e){e.preventDefault();var event=getEvent(e,true);if(!event){return;}
var el=this;set(el,'swipe:startTime',Date.now());set(el,'swipe:isHorizontal',true);set(el,'swipe:isVertical',true);set(el,'swipe:startX',event.pageX);set(el,'swipe:startY',event.pageY);enabled(el);}
return function(e){if(!__first_executed_1535262521671__){getEvent=include('browser.event.pointer');enabled=include('browser.event.gesture.swipe.methods.enabled');set=include('object.data.set');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),e);};}();exports['src::browser.event.gesture.swipe.methods.install']=function(){var onStart=void 0,getEventName=void 0;var __first_executed_1535262521671__=false;function main(el){el.addEventListener(getEventName(),onStart);}
return function(el){if(!__first_executed_1535262521671__){onStart=include('browser.event.gesture.swipe.methods.onStart');getEventName=include('browser.event.pointer.down');__first_executed_1535262521671__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.swipe.methods.uninstall']=function(){function main(el){}
return function(el){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el);};}();exports['src::browser.event.gesture.swipe']=function(){var Main=function(){function Main(){_classCallCheck(this,Main);}
_createClass(Main,null,[{key:'install',value:function install(){return include('browser.event.gesture.swipe.methods.install').apply(this,arguments);}},{key:'uninstall',value:function uninstall(){return include('browser.event.gesture.swipe.methods.uninstall').apply(this,arguments);}},{key:'handledEvents',get:function get(){return include('browser.event.gesture.swipe.properties.handleEvents').call(this);}}]);return Main;}();;return Main;}();exports['src::browser.html.element.style.set']=function(){function main(el,prop,value){el.style.setProperty(prop,value);}
return function(el,prop,value){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),el,prop,value);};}();exports['src::url.template.apply']=function(){function main(url,data){return url.replace(/\:([^\\\/\d]+)/g,function(match,name){return data[name]||'';});}
return function(url,data){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),url,data);};}();exports['src::is.string']=function(){var isType=void 0;var __first_executed_1535262521672__=false;function main(data){return isType(data,'string');}
return function(data){if(!__first_executed_1535262521672__){isType=include('is.type');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::url.isAbsolute']=function(){function main(url){return(/^https?\:\/{2}/.test(url));}
return function(url){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),url);};}();exports['src::url.join']=function(){var isAbsolute=void 0;var __first_executed_1535262521672__=false;var urlSuffixRe=/\/$/;function main(){var len=arguments.length,i=0,result=[];for(;i<len;i++){var part=(arguments.length<=i?undefined:arguments[i])||'';part=part.replace(urlSuffixRe,'');if(isAbsolute(part)){result.length=0;result.push(part);}else if(part){result.push(part);}}
return result.join('/');}
return function(){if(!__first_executed_1535262521672__){isAbsolute=include('url.isAbsolute');__first_executed_1535262521672__=true;}
for(var _len=arguments.length,urls=Array(_len),_key2=0;_key2<_len;_key2++){urls[_key2]=arguments[_key2];}
return main.call.apply(main,[function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this)].concat(urls));};}();exports['src::url.append']=function(){var isString=void 0;var __first_executed_1535262521672__=false;function main(url,data){var querystring=void 0;if(isString(data)){querystring=data;}else{var _require=require('querystring'),stringify=_require.stringify;querystring=stringify(data);}
if(url.includes('?')){return url+'&'+querystring;}
return url+'?'+querystring;}
return function(url,data){if(!__first_executed_1535262521672__){isString=include('is.string');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),url,data);};}();exports['src::xml.parse']=function(){var _require2=require('xmldom'),DOMParser=_require2.DOMParser,parser=new DOMParser();function main(){try{return parser.parseFromString(data,'text/xml');}catch(err){}
return parser.parseFromString('<xml/>','text/xml');}
return function(data){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::is.object']=function(){var isType=void 0;var __first_executed_1535262521672__=false;function main(data){return Object.prototype.toString.call(data)==='[object Object]';}
return function(data){if(!__first_executed_1535262521672__){isType=include('is.type');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::object.keys']=function(){var isObject=void 0;var __first_executed_1535262521672__=false;function main(data){return get_keys(data);}
function get_keys(data){var rootKey=arguments.length>1&&arguments[1]!==undefined?arguments[1]:'';var keys=Object.keys(data),result=[];var _iteratorNormalCompletion5=true;var _didIteratorError5=false;var _iteratorError5=undefined;try{for(var _iterator5=keys[Symbol.iterator](),_step5;!(_iteratorNormalCompletion5=(_step5=_iterator5.next()).done);_iteratorNormalCompletion5=true){var key=_step5.value;var value=data[key];if(isObject(value)){result.push.apply(result,_toConsumableArray(get_keys(value,''+rootKey+key+'.')));}else{result.push(''+rootKey+key);}}}catch(err){_didIteratorError5=true;_iteratorError5=err;}finally{try{if(!_iteratorNormalCompletion5&&_iterator5.return){_iterator5.return();}}finally{if(_didIteratorError5){throw _iteratorError5;}}}
return result;}
return function(data){if(!__first_executed_1535262521672__){isObject=include('is.object');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::is.array']=function(){var isType=void 0;var __first_executed_1535262521672__=false;function main(data){return Array.isArray(data);}
return function(data){if(!__first_executed_1535262521672__){isType=include('is.type');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::is.empty']=function(){var isArray=void 0;var __first_executed_1535262521672__=false;function main(data,allowEmptyString){return data==null||(!allowEmptyString?data==='':false)||isArray(data)&&data.length===0;}
return function(data){var allowEmptyString=arguments.length>1&&arguments[1]!==undefined?arguments[1]:false;if(!__first_executed_1535262521672__){isArray=include('is.array');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data,allowEmptyString);};}();exports['src::string.split']=function(){var isEmpty=void 0;var __first_executed_1535262521672__=false;function main(target,splitRe){return target.split(splitRe).filter(filter);}
function filter(target){return!isEmpty(target);}
return function(target,splitRe){if(!__first_executed_1535262521672__){isEmpty=include('is.empty');__first_executed_1535262521672__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,splitRe);};}();exports['src::object.set']=function(){var isObject=void 0,split=void 0;var __first_executed_1535262521673__=false;var splitRe=/\./;function main(target,key,value){if(splitRe.test(key)){var keys=split(key,splitRe);key=keys.pop();var _iteratorNormalCompletion6=true;var _didIteratorError6=false;var _iteratorError6=undefined;try{for(var _iterator6=keys[Symbol.iterator](),_step6;!(_iteratorNormalCompletion6=(_step6=_iterator6.next()).done);_iteratorNormalCompletion6=true){var _key3=_step6.value;var _data=target[_key3];if(!isObject(_data)){_data=target[_key3]={};}
target=_data;}}catch(err){_didIteratorError6=true;_iteratorError6=err;}finally{try{if(!_iteratorNormalCompletion6&&_iterator6.return){_iterator6.return();}}finally{if(_didIteratorError6){throw _iteratorError6;}}}
target[key]=value;}else{target[key]=value;}}
return function(target,key,value){if(!__first_executed_1535262521673__){isObject=include('is.object');split=include('string.split');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),target,key,value);};}();exports['src::object.get']=function(){var splitRe=/\./;function main(data,key){if(key){if(key in data){return data[key];}
var names=key.split(splitRe),prefix='';var _iteratorNormalCompletion7=true;var _didIteratorError7=false;var _iteratorError7=undefined;try{for(var _iterator7=names[Symbol.iterator](),_step7;!(_iteratorNormalCompletion7=(_step7=_iterator7.next()).done);_iteratorNormalCompletion7=true){var name=_step7.value;var _key4=''+prefix+name;if(!data){break;}
if(_key4 in data){data=data[_key4];prefix='';}else{prefix=_key4+'.';}}}catch(err){_didIteratorError7=true;_iteratorError7=err;}finally{try{if(!_iteratorNormalCompletion7&&_iterator7.return){_iterator7.return();}}finally{if(_didIteratorError7){throw _iteratorError7;}}}
if(prefix){return;}
return data;}
return data;}
return function(data,key){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data,key);};}();exports['src::object.assign']=function(){var getKeys=void 0,set=void 0,get=void 0;var __first_executed_1535262521673__=false;function main(dest,source){var keys=getKeys(source);var _iteratorNormalCompletion8=true;var _didIteratorError8=false;var _iteratorError8=undefined;try{for(var _iterator8=keys[Symbol.iterator](),_step8;!(_iteratorNormalCompletion8=(_step8=_iterator8.next()).done);_iteratorNormalCompletion8=true){var key=_step8.value;set(dest,key,get(source,key));}}catch(err){_didIteratorError8=true;_iteratorError8=err;}finally{try{if(!_iteratorNormalCompletion8&&_iterator8.return){_iterator8.return();}}finally{if(_didIteratorError8){throw _iteratorError8;}}}
return dest;}
return function(dest,source){if(!__first_executed_1535262521673__){getKeys=include('object.keys');set=include('object.set');get=include('object.get');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),dest,source);};}();exports['config::http']={"default":{"timeout":20000,"type":"json"}};exports['src::http.params.parse']=function(){var apply=void 0,isObject=void 0,isString=void 0,join=void 0,append=void 0,parse=void 0,assign=void 0,configHttp=void 0;var http=void 0;var __first_executed_1535262521673__=false;function main(uri,method,params){method=method.toUpperCase();var name=void 0;if(isString(params)){name=params;params={};}else if(isObject(params)){name=params.name||'default';delete params.name;}else{name='default';params={};}
var httpConfig=http[name];if(httpConfig){var rootPath=httpConfig.root,type=httpConfig.type,headers=httpConfig.headers,timeout=httpConfig.timeout,_process_type=process_type(type),requestType=_process_type.request,responseType=_process_type.response;var _params=params,query=_params.query,path=_params.path,body=_params.body,userTimeout=_params.timeout;return assign({uri:append(join(rootPath,apply(uri,path)),{_dc:Date.now()}),timeout:timeout,requestTimeout:timeout||0,method:method,headers:headers,qs:query,transform:transform(responseType)},process_body(body,requestType),process_timeout(userTimeout));}
throw new Error('试图请求未注册的路径');}
function process_timeout(timeout){if(timeout){return{timeout:timeout,requestTimeout:timeout};}
return{};}
function process_body(body,type){switch(type){case'json':return{body:body,headers:{'content-type':'application/json'},json:true};case'xml':return{headers:{'content-type':'application/xml'},body:body};case'form':return{formData:body};case'html':return{headers:{'content-type':'text/html'},body:body};}
return{body:body};;}
function process_type(type){if(isObject(type)){var request=type.request,response=type.response;return{request:request,response:response};}else if(isString(type)){return{request:type,response:type};}
return{};}
function transform_json(body){if(isString(body)){return JSON.parse(body);}
return body;}
function transform_xml(body){return parse(body);}
function transform_html(body){}
function transform_empty(body){return body;}
function transform(type){switch(type){case'json':return transform_json;case'xml':return transform_xml;case'html':return transform_html;}
return transform_empty;}
return function(uri,method,params){if(!__first_executed_1535262521673__){apply=include('url.template.apply');isObject=include('is.object.simple');isString=include('is.string');join=include('url.join');append=include('url.append');parse=include('xml.parse');assign=include('object.assign');configHttp=include('config::http');http=config('http');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),uri,method,params);};}();exports['src::http.methods.get']=function(){var parse=void 0;var __first_executed_1535262521673__=false;function main(uri,params){return require('request-promise')(parse(uri,'get',params));}
return function(uri,params){if(!__first_executed_1535262521673__){parse=include('http.params.parse');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),uri,params);};}();exports['src::http.methods.post']=function(){var parse=void 0;var __first_executed_1535262521673__=false;function main(uri,params){return require('request-promise')(parse(uri,'post',params));}
return function(uri,params){if(!__first_executed_1535262521673__){parse=include('http.params.parse');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),uri,params);};}();exports['src::http.methods.put']=function(){var parse=void 0;var __first_executed_1535262521673__=false;function main(uri,params){return require('request-promise')(parse(uri,'put',params));}
return function(uri,params){if(!__first_executed_1535262521673__){parse=include('http.params.parse');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),uri,params);};}();exports['src::http.methods.delete']=function(){var parse=void 0;var __first_executed_1535262521673__=false;function main(uri,params){return require('request-promise')(parse(uri,'delete',params));}
return function(uri,params){if(!__first_executed_1535262521673__){parse=include('http.params.parse');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),uri,params);};}();exports['src::http']=function(){var Main=function(){function Main(){_classCallCheck(this,Main);}
_createClass(Main,null,[{key:'get',value:function get(){return include('http.methods.get').apply(this,arguments);}},{key:'post',value:function post(){return include('http.methods.post').apply(this,arguments);}},{key:'put',value:function put(){return include('http.methods.put').apply(this,arguments);}},{key:'delete',value:function _delete(){return include('http.methods.delete').apply(this,arguments);}}]);return Main;}();;return Main;}();exports['src::connection.message.is']=function(){var isObject=void 0;var __first_executed_1535262521673__=false;function main(data){if(isObject(data)){return data.hasOwnProperty('id')&&data.hasOwnProperty('action');}
return false;}
return function(data){if(!__first_executed_1535262521673__){isObject=include('is.object.simple');__first_executed_1535262521673__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),data);};}();exports['src::connection.message.is.reply']=function(){var is=void 0;var __first_executed_1535262521674__=false;function main(message){return is(message)&&message.hasOwnProperty('reply');}
return function(message){if(!__first_executed_1535262521674__){is=include('connection.message.is');__first_executed_1535262521674__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),message);};}();exports['src::connection.message.reply.result']=function(){function main(replyMessage){var reply=replyMessage.reply;if(reply!==false){var _data2=reply.data;return _data2;}}
return function(replyMessage){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),replyMessage);};}();exports['src::connection.sender.send']=function(){var isReply=void 0,isReplyTo=void 0,result=void 0;var __first_executed_1535262521674__=false;function main(sender,implementName,message){return new Promise(function(callback){include(implementName)(sender,message,function(replyMessage){if(isReplyTo(replyMessage,message)){callback(result(replyMessage));return true;}});});}
return function(sender,implementName,message){if(!__first_executed_1535262521674__){isReply=include('connection.message.is.reply');isReplyTo=include('connection.message.is.reply.to');result=include('connection.message.reply.result');__first_executed_1535262521674__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),sender,implementName,message);};}();exports['src::connection.sender.send.window']=function(){function main(window,message,fn){window.postMessage(message,'*');var callback=function callback(_ref4){var data=_ref4.data;if(fn(data)===true){window.removeEventListener('message',callback);}};window.addEventListener('message',callback);}
return function(window,message,fn){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),window,message,fn);};}();exports['src::connection.message.package']=function(){var count=0;function main(){return{id:Date.now()+'-'+++count,action:action,data:data};}
return function(action,data){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),action,data);};}();exports['src::connection.window.send']=function(){var send=void 0,connectionSenderSendWindow=void 0,doPackage=void 0;var __first_executed_1535262521674__=false;function main(window,action,data){return send(window,'connection.sender.send.window',doPackage(action,data));}
return function(window,action,data){if(!__first_executed_1535262521674__){send=include('connection.sender.send');connectionSenderSendWindow=include('connection.sender.send.window');doPackage=include('connection.message.package');__first_executed_1535262521674__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),window,action,data);};}();exports['src::connection.message.is.main']=function(){var is=void 0;var __first_executed_1535262521674__=false;function main(message){return is(message)&&!message.hasOwnProperty('reply');}
return function(message){if(!__first_executed_1535262521674__){is=include('connection.message.is');__first_executed_1535262521674__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),message);};}();exports['src::connection.message.reply']=function(){function main(message,data){if(data){return _extends({},message,{reply:{data:data}});}
return _extends({},message,{reply:false});}
return function(message,data){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),message,data);};}();exports['src::function.empty']=function(){var emptyFn=function emptyFn(){};function main(){return emptyFn;}
return function(){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this));};}();exports['src::connection.receiver.receive']=function(){var isMain=void 0,reply=void 0,isString=void 0,isFunction=void 0,emptyFn=void 0;var __first_executed_1535262521674__=false;function main(receiver,implementName,replyName,actionName){var _this=this;var actionFn=void 0;if(isString(actionName)){actionFn=include(actionName);}else if(isString(actionName)){actionFn=actionName;}else{actionFn=emptyFn();}
include(implementName)(receiver).then(function(){var _ref5=_asyncToGenerator(regeneratorRuntime.mark(function _callee(message){return regeneratorRuntime.wrap(function _callee$(_context){while(1){switch(_context.prev=_context.next){case 0:if(!isMain(message)){_context.next=11;break;}
_context.t0=include(replyName);_context.t1=receiver;_context.t2=reply;_context.t3=reply;_context.t4=message;_context.next=8;return actionFn(message);case 8:_context.t5=_context.sent;_context.t6=(0,_context.t2)(_context.t3,_context.t4,_context.t5);(0,_context.t0)(_context.t1,_context.t6);case 11:case'end':return _context.stop();}}},_callee,_this);}));return function(_x7){return _ref5.apply(this,arguments);};}());}
return function(receiver,implementName,replyName,actionName){if(!__first_executed_1535262521674__){isMain=include('connection.message.is.main');reply=include('connection.message.reply');isString=include('is.string');isFunction=include('is.function');emptyFn=include('function.empty');__first_executed_1535262521674__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),receiver,implementName,replyName,actionName);};}();exports['src::connection.receiver.receive.window']=function(){function main(window){window.addEventListener('message',function(_ref6){var data=_ref6.data;callback(data);});}
return function(window){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),window);};}();exports['src::connection.receiver.reply.window']=function(){function main(window,message){window.postMessage(message,'*');}
return function(window,message){return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),window,message);};}();exports['src::connection.window.receive']=function(){var receive=void 0,connectionReceiverReceiveWindow=void 0,connectionReceiverReplyWindow=void 0;var __first_executed_1535262521674__=false;function main(window,actionFn){receive(window,'connection.receiver.receive.window','connection.receiver.reply.window',actionFn);}
return function(window,actionFn){if(!__first_executed_1535262521674__){receive=include('connection.receiver.receive');connectionReceiverReceiveWindow=include('connection.receiver.receive.window');connectionReceiverReplyWindow=include('connection.receiver.reply.window');__first_executed_1535262521674__=true;}
return main.call(function(){var me=this,target=void 0;if(typeof global!=='undefined'){target=global;}else{target=window;}
return me===target?main:me;}.call(this),window,actionFn);};}();exports['src::browser.setAnimationFrame']=include('src::browser.animationFrame.set');}).call(window[vue-browser]={});